<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-29T01:50:43Z" name="Default suite" finished-at="2021-12-29T01:55:51Z" duration-ms="307318">
    <groups>
    </groups>
    <test started-at="2021-12-29T01:50:43Z" name="Default test" finished-at="2021-12-29T01:55:51Z" duration-ms="307318">
      <class name="com.timp.test.BRB.ComentarioLibre">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.timp.test.BRB.ComentarioLibre@5b367418]" started-at="2021-12-29T01:50:43Z" name="beforeClass" finished-at="2021-12-29T01:51:33Z" duration-ms="49347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="comentarioLibre()[pri:0, instance:com.timp.test.BRB.ComentarioLibre@5b367418]" started-at="2021-12-29T01:51:33Z" name="comentarioLibre" finished-at="2021-12-29T01:55:51Z" duration-ms="257921" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Os comentários não foram os ingresados expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Os comentários não foram os ingresados expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.timp.test.BRB.ComentarioLibre.comentarioLibre(ComentarioLibre.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- comentarioLibre -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.timp.test.BRB.ComentarioLibre@5b367418]" started-at="2021-12-29T01:55:51Z" name="afterClass" finished-at="2021-12-29T01:55:51Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.timp.test.BRB.ComentarioLibre -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
