<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-17T02:26:38Z" name="Default suite" finished-at="2020-11-17T02:29:01Z" duration-ms="142558">
    <groups>
    </groups>
    <test started-at="2020-11-17T02:26:38Z" name="Default test" finished-at="2020-11-17T02:29:01Z" duration-ms="142558">
      <class name="com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar@6bf08014]" started-at="2020-11-16T20:26:38Z" name="beforeClass" finished-at="2020-11-16T20:27:32Z" duration-ms="53565" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="login()[pri:0, instance:com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar@6bf08014]" started-at="2020-11-16T20:27:32Z" name="login" finished-at="2020-11-16T20:27:40Z" duration-ms="8501" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="acessarMDR()[pri:0, instance:com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar@6bf08014]" started-at="2020-11-16T20:27:40Z" name="acessarMDR" finished-at="2020-11-16T20:28:47Z" duration-ms="66219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acessarMDR -->
        <test-method signature="atualizar()[pri:0, instance:com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar@6bf08014]" started-at="2020-11-16T20:28:47Z" name="atualizar" finished-at="2020-11-16T20:29:00Z" duration-ms="13613" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Não foi possivel atualizar os registros expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Não foi possivel atualizar os registros expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar.atualizar(MovimentoSCANCAtualizar.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- atualizar -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar@6bf08014]" started-at="2020-11-16T20:29:00Z" name="afterClass" finished-at="2020-11-16T20:29:01Z" duration-ms="623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.timp.test.MDR.SCANC.MovimentoSCANC.MovimentoSCANCAtualizar -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
